_THUNK_API_v(enable);
_THUNK_API_v(disable);
_THUNK_API_2(UBYTE, peekb, UWORD, seg, UWORD, ofs);
_THUNK_API_2(UWORD, peekw, UWORD, seg, UWORD, ofs);
_THUNK_API_2(ULONG, peekl, UWORD, seg, UWORD, ofs);
_THUNK_API_3v(pokeb, UWORD, seg, UWORD, ofs, UBYTE, b);
_THUNK_API_3v(pokew, UWORD, seg, UWORD, ofs, UWORD, w);
_THUNK_API_3v(pokel, UWORD, seg, UWORD, ofs, ULONG, l);
_THUNK_API_0(UWORD, getCS);
_THUNK_API_0(UWORD, getSS);
_THUNK_API_1(void *, short_ptr, UWORD, offs);
_THUNK_API_2(UWORD, mk_offs, UBYTE *, data, UWORD, len);
