name: Build and test
on:
  pull_request:
    types:
      - opened
      - ready_for_review
      - reopened
      - synchronize
  push:

env:
  DIR_TEST_DOSEMU: test-dosemu
  DIR_INSTALLED_FDPP: test-dosemu/installed-fdpp
  USE_DOSEMU_BRANCH: devel

jobs:
  Build_and_test:
    name: Build and test

    if: contains(github.event.head_commit.message, '[skip ci]') == false

    runs-on: ubuntu-26.04

    steps:
    - name: Checkout
      uses: actions/checkout@v6

    - name: Add an ACL to KVM for ourselves
      run: |
          echo 'SUBSYSTEM=="misc", KERNEL=="kvm", RUN+="/usr/bin/setfacl -m u:'${USER}':rw- /dev/kvm"' | sudo tee /etc/udev/rules.d/99-kvm4dosemu2.rules
          sudo udevadm control --reload-rules
          sudo udevadm trigger --name-match=kvm

    - name: Information
      run: |
        #
        echo "::group::CPU"
        lscpu
        echo "::endgroup::"

        echo "::group::Kernel Config"
        cat /boot/config-$(uname -r)
        echo "::endgroup::"

        echo "::group::Kernel Modules"
        sudo lsmod
        echo "::endgroup::"

        echo "::group::Kernel Parameters (sysctl)"
        sysctl -a
        echo "::endgroup::"

        echo "::group::KVM permissions"
        getfacl -p /dev/kvm
        echo "::endgroup::"

    - name: Package install
      run: ./ci_prereq.sh

    - name: Build
      run: ./ci_build.sh

    - name: Set up test environment
      run: ./ci_setup_test.sh

    - name: Test
      id: test
      run: ./ci_test.sh

    - name: Upload failure logs
      if: ${{ always() && (steps.test.outcome == 'failure') }}
      uses: actions/upload-artifact@v6
      with:
        name: failure-logs
        path: ${{ env.DIR_TEST_DOSEMU }}/test_*
